project:
  type: website

website:
  title: "Lightbridge"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Lightbridge-KS
format:
  html:
    theme: Flatly
    css: styles.css



