project:
  type: website

# My Inform
author: "Kittipos Sirivongrungson"

website:
  title: "Lightbridge"
  navbar:
    right:
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/Lightbridge-KS
  page-footer:
    center:
      - icon: github
        href: https://github.com/Lightbridge-KS
    right:
      - text: "License"
        file: license.qmd
format:
  html:
    theme: Flatly
    css: styles.css
    html-math-method: mathjax # mathjax (default), katex, mathml

# freeze computational output
# (see https://quarto.org/docs/projects/code-execution.html#freeze)
execute: 
  freeze: true

csl: "_assets/csl/elsevier-with-titles.csl"

#"_assets/csl/american-statistical-association.csl"
